spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    #content-type: text/html
    cache: false
    prefix: classpath:/templates/

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 分布式文件系统FDFS配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  resHost: 192.168.1.103
  storagePort: 8080
  #thumbImage: #缩略图生成参数，可选
  #  width: 150
  #  height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 192.168.1.103:22122


server:
  port: 8888
