server:
  port: 8008

spring:
  rabbitmq:
    host: 192.168.197.97
    port: 5672
    username: yxd
    password: 123456
    virtual-host: /
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true