spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: gzbus
    password: gzbus
    virtual-host: /
    publisher-confirms: true  #  消息发送到交换机确认机制,是否确认回调
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual # 手动确认
        concurrency: 1
        max-concurrency: 10
        retry:
          enabled: true