server:
  port: 8009

##########################################
######        kafka单机配置         #######
##########################################
spring:
  kafka:
    bootstrap-servers: 192.168.197.97:9092 #kafka的访问地址，多个用","隔开
    consumer:
      enable-auto-commit: true
      group-id: kafka #群组ID
      auto-offset-reset: earliest #启东时接收没有接收到的数据

##########################################
######        kafka集群配置         #######
##########################################
#spring:
#  kafka:
#    consumer:
#      enable-auto-commit: true
#      group-id: kafka
#      auto-offset-reset: earliest
#      bootstrap-servers: 192.168.5.11:9092
#    producer:
#      bootstrap-servers: 192.168.5.10:9092